name: lint
on: [push, pull_request]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt-get -y install pylint
      - run: pylint --fail-under 10 patcher.py
