name: lint
on: [push, pull_request]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install pylint
      - run: ls -l
      - run: pylint --fail-under 10 patcher.py
